language: java
jdk:
  - openjdk11

branches:
  only:
    - main

### application.yml 암호화 ###
before_install: openssl aes-256-cbc -K $encrypted_02497ee72256_key -iv $encrypted_02497ee72256_iv -in application.yml.enc -out ./application.yml -d

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
  script: "./gradlew clean build"
