language: java
jdk:
  - openjdk11

branches:
  only:
    - main

### application.yml 암호화 ###
before_install: openssl aes-256-cbc -K $encrypted_c1e35b1b62fe_key -iv $encrypted_c1e35b1b62fe_iv -in application.yml.enc -out ./src/main/resources/application.yml -d

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
  script: "./gradlew clean build"

# 배포 #
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: main